---
data:
  project_dir: ""
  train:
    paths:
      - "data/train.chinese_word.txt"
  eval:
    paths:
      - "data/eval.chinese_word.txt"
  infer:
    paths:
      - "data/test.chinese_word.txt"
  task:
    name: TextClsTask
    preparer:
      enable: true
      name: TextClsPreparer
      done_sign: "exp/prepare.done"
      reuse: true
    use_dense: false
    language: chinese
    split_by_space: false
    use_word: true
    vocab_min_frequency: 20
    use_custom_vocab: True
    text_vocab: "data/text_vocab.chinese_word.txt"
    label_vocab: "exp/label_vocab.txt"
    max_seq_len: 1024
    num_parallel_calls: 12
    num_prefetch_batch: 2
    shuffle_buffer_size: 1000
    need_shuffle: true
    batch_size: 32
    epochs: 2
    classes:
      positive_id: 1
      num_classes: 2
      vocab:
        0: 0
        1: 1
model:
  name: SeqclassCNNModel
  type: keras
  use_pre_train_emb: false
  pre_train_emb_path: ""
  embedding_path: "egs/trec/text_cls/v1/exp/embeding.pkl"

  net:
    structure:
      embedding_size: 128
      emb_trainable: true
      num_units: 128
      num_layers: 2
      dropout_rate: 0.5
      pooling:
        - max
        - mean
      filter_sizes:
        - 3
        - 4
        - 5
      num_filters: 128
      l2_reg_lambda: 0

solver:
  name: RawClassSolver
  adversarial:
    enable: false # whether to using adversiral training
    adv_alpha: 0.5 # adviseral alpha of loss
    adv_epslion: 0.1 # adviseral example epslion
  model_average:
    enable: false # use average model
    var_avg_decay: 0.99 # the decay rate of varaibles
  optimizer:
    name: adam
    loss: CrossEntropyLoss
    label_smoothing: 0.0 # label smoothing rate
    learning_rate:
      rate: 0.0001 # learning rate of Adam optimizer
      type:  exp_decay # learning rate type
      decay_rate: 0.99  # the lr decay rate
      decay_steps: 100  # the lr decay_step for optimizer
    clip_global_norm: 3.0 # clip global norm
  metrics:
    pos_label: 1 # int, same to sklearn
    cals:
      - name: AccuracyCal
        arguments: Null
      - name: PrecisionCal
        arguments:
          average: 'macro'
      - name: RecallCal
        arguments:
          average: 'macro'
      - name: F1ScoreCal
        arguments:
          average: 'weighted'
  postproc:
    name: SavePredPostProc
    res_file: "exp/infer_res.txt"
  saver:
    model_path: "exp/cnn-cls/ckpt"
    max_to_keep: 30
    save_checkpoint_steps: 30
    print_every: 10
  service:
    model_path: "exp/cnn-cls/service"
    model_version: "1"
    input_sentence: "input_sentence:0"
    input_x: "seqclass_cnn_model/input_x:0"
    score: "score:0"
    preds: "preds:0"

  run_config:
    tf_random_seed: null
    allow_soft_placement: true
    log_device_placement: false
    intra_op_parallelism_threads: 10
    inter_op_parallelism_threads: 10
    allow_growth: true
