---
data:
  project_dir: ""
  train:
    paths:
      - "data/train.txt"
  eval:
    paths:
      - "data/dev.txt"
  infer:
    paths:
      - "data/test.txt"
  task:
    name: TextSeqLabelTask
    preparer:
      enable: true
      name: TextSeqLabelPreparer
      done_sign: "exp/prepare.done"
      reuse: true
    use_dense: false
    language: english
    vocab_min_frequency: 0
    use_custom_vocab: True
    text_vocab: "data/text_vocab.txt"
    label_vocab: "data/label_vocab.txt"
    max_seq_len: 30
    batch_size: 10
    epochs: 2
    num_parallel_calls: 12
    num_prefetch_batch: 2
    shuffle_buffer_size: 2000
    need_shuffle: true
    classes:
      positive_id: 1
      num_classes: 9
      vocab:
        O: 0
        B-PER: 1
        I-PER: 2
        B-LOC: 3
        I-LOC: 4
        B-ORG: 5
        I-ORG: 6
        B-MISC: 7
        I-MISC: 8

model:
  name: BilstmCrfModel
  type: keras # raw, keras or eager model
  use_pre_train_emb: False
  net:
    structure:
      embedding_size: 300
      cell_type: lstm
      cell_dim: 100
      num_units: 300
      num_layers: 1
      batch_size: 10
      max_len: 30
      dropout_rate: 0.5
      l2_reg_lambda: 0
      fc_dim: 100

solver:
  name: RawSeqLabelSolver
  adversarial:
    enable: false # whether to using adversiral training
    adv_alpha: 0.5 # adviseral alpha of loss
    adv_epslion: 0.1 # adviseral example epslion
  model_average:
    enable: false # use average model
    var_avg_decay: 0.99 # the decay rate of varaibles
  optimizer:
    name: adam
    loss: CrfLoss
    label_smoothing: 0.0 # label smoothing rate
    learning_rate:
      rate: 0.001 # learning rate of Adam optimizer
      type:  exp_decay # learning rate type
      decay_rate: 0.99  # the lr decay rate
      decay_steps: 100  # the lr decay_step for optimizer
    batch_size: 10
    epochs: 1
    clip_global_norm: 3.0 # clip global norm
  metrics:
    pos_label: 1
    cals:
      - name: CrfCal
        arguments:
          label_vocab_path: "data/label_vocab.txt"
  postproc:
    name: SavePredEntityPostProc
    res_file: "res/infer_res.txt"
  saver:
    model_path: "ckpt/bilstmcrf/"
    max_to_keep: 10
    save_checkpoint_steps: 20
    print_every: 10
  service:
    model_path: "exp/bilstmcrf/service"
    model_version: "2"
  run_config:
    tf_random_seed: null
    allow_soft_placement: true
    log_device_placement: false
    intra_op_parallelism_threads: 10
    inter_op_parallelism_threads: 10
    allow_growth: true
